/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedWorkRegRouteImport } from './routes/_authenticated/work.$reg'
import { Route as AuthenticatedPrintRegRouteImport } from './routes/_authenticated/print.$reg'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkRegRoute = AuthenticatedWorkRegRouteImport.update({
  id: '/$reg',
  path: '/$reg',
  getParentRoute: () => AuthenticatedWorkRoute,
} as any)
const AuthenticatedPrintRegRoute = AuthenticatedPrintRegRouteImport.update({
  id: '/print/$reg',
  path: '/print/$reg',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/print/$reg': typeof AuthenticatedPrintRegRoute
  '/work/$reg': typeof AuthenticatedWorkRegRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/print/$reg': typeof AuthenticatedPrintRegRoute
  '/work/$reg': typeof AuthenticatedWorkRegRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/work': typeof AuthenticatedWorkRouteWithChildren
  '/_authenticated/print/$reg': typeof AuthenticatedPrintRegRoute
  '/_authenticated/work/$reg': typeof AuthenticatedWorkRegRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/work' | '/print/$reg' | '/work/$reg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/work' | '/print/$reg' | '/work/$reg'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/work'
    | '/_authenticated/print/$reg'
    | '/_authenticated/work/$reg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/$reg': {
      id: '/_authenticated/work/$reg'
      path: '/$reg'
      fullPath: '/work/$reg'
      preLoaderRoute: typeof AuthenticatedWorkRegRouteImport
      parentRoute: typeof AuthenticatedWorkRoute
    }
    '/_authenticated/print/$reg': {
      id: '/_authenticated/print/$reg'
      path: '/print/$reg'
      fullPath: '/print/$reg'
      preLoaderRoute: typeof AuthenticatedPrintRegRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedWorkRouteChildren {
  AuthenticatedWorkRegRoute: typeof AuthenticatedWorkRegRoute
}

const AuthenticatedWorkRouteChildren: AuthenticatedWorkRouteChildren = {
  AuthenticatedWorkRegRoute: AuthenticatedWorkRegRoute,
}

const AuthenticatedWorkRouteWithChildren =
  AuthenticatedWorkRoute._addFileChildren(AuthenticatedWorkRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRouteWithChildren
  AuthenticatedPrintRegRoute: typeof AuthenticatedPrintRegRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkRoute: AuthenticatedWorkRouteWithChildren,
  AuthenticatedPrintRegRoute: AuthenticatedPrintRegRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
